name: Khoram2Ry
generate:
  swiftVersion: '5.0'
  minimumXcodeGenVersion: '2.38.0'
options:
  deploymentTarget:
    iOS: '15.0'
targets:
  Khoram2Ry:
    type: application
    platform: iOS
    sources:
      - path: Khoram2Ry
    resources:
      - path: ../dist
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.khoram2ry.app
        INFOPLIST_FILE: Khoram2Ry/Info.plist
        CODE_SIGN_ENTITLEMENTS: Khoram2Ry/Khoram2Ry.entitlements
        SWIFT_VERSION: '5.0'
        TARGETED_DEVICE_FAMILY: '1,2'
        DEVELOPMENT_TEAM: $(IOS_TEAM_ID)
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: $(IOS_APP_PROFILE)
    dependencies:
      - target: Khoram2RyPacketTunnel
        embed: true
  Khoram2RyPacketTunnel:
    type: app-extension
    platform: iOS
    sources:
      - path: Khoram2RyPacketTunnel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.khoram2ry.app.PacketTunnel
        INFOPLIST_FILE: Khoram2RyPacketTunnel/Info.plist
        CODE_SIGN_ENTITLEMENTS: Khoram2RyPacketTunnel/Khoram2RyPacketTunnel.entitlements
        SWIFT_VERSION: '5.0'
        DEVELOPMENT_TEAM: $(IOS_TEAM_ID)
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: $(IOS_EXTENSION_PROFILE)
